export function page() {
  return `<!doctype html>
<html lang="pt">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover">
<meta name="theme-color" content="#090d14">
<title>Meme AI · V2.7</title>
<style>
:root{color-scheme:dark;font-family:Inter,ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;color:#eef2f8;background:#090d14;--bg:#090d14;--panel:#111925;--panel2:#0c131d;--line:#263449;--muted:#9eacc0;--soft:#cbd5e2;--green:#79dfa0;--red:#ff8791;--yellow:#ffd178;--blue:#91baff}
*{box-sizing:border-box;-webkit-tap-highlight-color:transparent}
html{min-height:100%;scroll-behavior:smooth;background:var(--bg)}
body{margin:0;min-height:100vh;background:radial-gradient(ellipse at 62% -20%,#19283a 0,#0c121b 40%,var(--bg) 78%);color:#eef2f8}
button,select{font:inherit}button{border:0;cursor:pointer}button:disabled{opacity:.55;cursor:wait}a{color:inherit}
.app{max-width:1220px;margin:0 auto;padding:24px 22px calc(100px + env(safe-area-inset-bottom))}
.header{display:flex;align-items:center;justify-content:space-between;gap:14px;margin:2px 0 22px}
.brand{display:flex;align-items:center;gap:12px;min-width:0}.logo{width:46px;height:46px;border-radius:15px;background:linear-gradient(145deg,#244331,#14291f);color:#9cf0b8;display:grid;place-items:center;font-weight:950;font-size:16px;box-shadow:0 8px 24px rgba(50,170,100,.12)}
.brand h1{font-size:24px;line-height:1;margin:0;font-weight:900;letter-spacing:-.035em}.brand p{margin:6px 0 0;color:var(--muted);font-size:12px}.status-dot{width:8px;height:8px;border-radius:50%;display:inline-block;background:var(--green);margin-right:7px;box-shadow:0 0 12px #79dfa055}
.scan-btn{height:46px;min-width:112px;padding:0 18px;border-radius:13px;background:var(--green);color:#08130c;font-size:12px;font-weight:950;letter-spacing:.04em;box-shadow:0 8px 24px #43b97522}.scan-btn:hover{background:#9aefb5}
.hero{position:relative;overflow:hidden;border:1px solid #2b3b50;border-radius:24px;background:linear-gradient(120deg,#142235,#111925 64%,#12251e);padding:23px;box-shadow:0 18px 55px #0003}
.hero:after{content:"";position:absolute;width:220px;height:220px;right:-100px;top:-130px;border-radius:50%;background:#68d99018;filter:blur(5px);pointer-events:none}
.hero-top{position:relative;z-index:1;display:flex;align-items:flex-start;justify-content:space-between;gap:14px}.kicker{font-size:10px;color:#a7c0dc;font-weight:900;letter-spacing:.13em;text-transform:uppercase}.hero h2{margin:7px 0 5px;font-size:30px;line-height:1.16;letter-spacing:-.04em}.hero-copy{max-width:720px;margin:0;color:#b4c0cf;font-size:13px;line-height:1.55}.last-scan{color:#91a1b5;font-size:11px;margin-top:11px}.count-pill{display:inline-flex;align-items:center;justify-content:center;background:#172334;border:1px solid #31445d;border-radius:999px;padding:8px 12px;color:#d2dceb;font-size:11px;font-weight:850;white-space:nowrap}
.hero-stats{position:relative;z-index:1;display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:10px;margin-top:20px}.hero-stat{min-width:0;background:#0b131edb;border:1px solid #26384d;border-radius:14px;padding:12px 14px}.hero-stat span{display:block;color:#a1b0c3;font-size:11px}.hero-stat b{display:block;margin-top:5px;color:#f3f7fc;font-size:22px;font-weight:900;letter-spacing:-.03em}
.section{display:none;animation:enter .18s ease}.section.active{display:block}@keyframes enter{from{opacity:.45;transform:translateY(4px)}to{opacity:1;transform:none}}
.section-head{display:flex;justify-content:space-between;align-items:center;gap:14px;margin:26px 2px 14px}.section-head h2{font-size:20px;line-height:1.2;margin:0;letter-spacing:-.025em}.section-head p{font-size:12px;line-height:1.5;color:var(--muted);margin:5px 0 0}
.filters-row{display:flex;align-items:center;gap:9px;flex-wrap:wrap;margin:0 0 14px}select{appearance:none;background:#121c2a;color:#e7edf6;border:1px solid #304158;border-radius:11px;padding:11px 36px 11px 13px;font-size:12px;font-weight:750;min-width:160px}select:focus,button:focus-visible,a:focus-visible,summary:focus-visible{outline:3px solid #79dfa077;outline-offset:2px}
.list{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:13px}.token{min-width:0;padding:16px;border:1px solid #29394e;border-radius:19px;background:linear-gradient(150deg,#141e2b,#101722 72%);box-shadow:0 10px 28px #0002}.token.alert{border-color:#68542d;box-shadow:0 8px 25px #f0b94a0d}.token-head{display:flex;align-items:flex-start;justify-content:space-between;gap:12px}.token-main{display:flex;align-items:center;gap:10px;min-width:0}.rank{width:32px;height:32px;flex:none;border-radius:11px;background:#1b2939;color:#b9c9dc;display:grid;place-items:center;font-size:10px;font-weight:900}.symbol{max-width:180px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;color:#f4f7fb;font-size:16px;font-weight:950}.name{max-width:210px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;color:#9eacc0;font-size:11px;margin-top:3px}.badges{display:flex;gap:5px;flex-wrap:wrap;margin-top:7px}.badge{display:inline-flex;align-items:center;padding:4px 7px;border:1px solid #314158;border-radius:999px;background:#172231;color:#c2cede;font-size:9px;font-weight:850}.badge.alert{background:#302713;border-color:#69532a;color:#ffd178}.scorebox{text-align:right;flex:none}.score{font-size:27px;line-height:1;font-weight:950;letter-spacing:-.05em;color:#f4f7fb}.scorelabel{margin-top:4px;color:#91a0b4;font-size:9px;font-weight:850;letter-spacing:.08em}
.quality-pill{display:inline-flex;align-items:center;width:max-content;margin-top:12px;padding:7px 10px;border:1px solid transparent;border-radius:999px;font-size:11px;font-weight:900}.quality-favorable{background:#153424;border-color:#2c6945;color:#9af0b8}.quality-caution{background:#302713;border-color:#695329;color:#ffd178}.quality-high-risk{background:#351b22;border-color:#71323e;color:#ff9ca5}.quality-learning{background:#192b42;border-color:#355782;color:#a6c7ff}
.social-block{margin-top:12px}.social-title{margin-bottom:6px;color:#d1dce9;font-size:11px;font-weight:850}.social-links{display:flex;gap:7px;flex-wrap:wrap}.social-link{display:inline-flex;align-items:center;gap:6px;padding:7px 9px;border:1px solid #304158;border-radius:9px;background:#152133;color:#b7d0ff;text-decoration:none;font-size:10px;font-weight:800}.social-link:hover{background:#1b2b40;border-color:#49688d}.social-link-icon{width:18px;height:18px;border-radius:6px;background:#22334a;display:grid;place-items:center;font-size:10px;color:#cae0ff}.social-note{font-size:10px;color:#91a2b6;margin-top:5px}
.scorebar{height:5px;background:#273449;border-radius:999px;overflow:hidden;margin:13px 0}.scorebar i{display:block;height:100%;border-radius:999px;background:linear-gradient(90deg,#70d99b,#a4efb9)}.forecast-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:7px;margin-top:10px}.forecast-cell{min-width:0;background:#0c141f;border:1px solid #29394e;border-radius:12px;padding:10px 9px}.forecast-cell span{display:block;color:#a0adbf;font-size:9px;font-weight:750;line-height:1.45}.forecast-cell b{display:block;margin-top:5px;color:#f0f4fa;font-size:12px}.forecast-note{margin-top:7px;color:#9aa9bc;font-size:10px;line-height:1.5}.model-signal{display:inline-block;margin-top:7px;padding:4px 8px;border:1px solid #2d7049;border-radius:999px;background:#163624;color:#a0f1ba;font-size:9px;font-weight:900}
.keygrid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:7px;margin-top:12px}.metric{min-width:0;padding:9px;border:1px solid #1f2c3d;border-radius:11px;background:#0c141e}.metric span{display:block;color:#9eacc0;font-size:9px;font-weight:750;line-height:1.35}.metric b{display:block;margin-top:4px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;color:#edf2f8;font-size:12px}.positive{color:#82e4a7!important}.negative{color:#ff8994!important}.neutral{color:#e5ebf3!important}
.details{margin-top:12px;padding-top:10px;border-top:1px solid #293548}.details summary{display:flex;justify-content:space-between;cursor:pointer;list-style:none;color:#c5d1df;font-size:11px;font-weight:850}.details summary::-webkit-details-marker{display:none}.details summary:after{content:"+";font-size:15px}.details[open] summary:after{content:"−"}.factor-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:7px;margin-top:10px}.factor{display:flex;justify-content:space-between;gap:5px;padding:8px;border-radius:9px;background:#0b121b;color:#b3c0d0;font-size:10px}.factor b{color:#e3eaf3;font-size:10px}.flags{margin-top:9px;color:#c5d1df;font-size:10px;line-height:1.5}.address{margin-top:8px;word-break:break-all;color:#8392a6;font-size:9px}.open-token-btn{margin-top:10px;padding:10px 12px;border:1px solid #41605a;border-radius:10px;background:#142b24;color:#a1edba;font-size:11px;font-weight:850}.open-token-btn:hover{background:#1b3a2e;border-color:#5b8d73}
.info-card,.history-card{margin-top:10px;padding:16px;border:1px solid #29394e;border-radius:17px;background:linear-gradient(150deg,#141e2b,#101722)}.info-card h3{margin:0 0 7px;color:#edf2f8;font-size:15px}.info-card p{margin:7px 0;color:#a9b6c8;font-size:12px;line-height:1.6}.history-list{display:grid;gap:9px}.history-head{display:flex;justify-content:space-between;align-items:center;gap:10px}.history-symbol{font-size:14px;font-weight:900}.history-status{font-size:11px;font-weight:900}.history-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:7px;margin-top:10px}.mini{min-width:0;padding:8px;border:1px solid #1f2c3d;border-radius:9px;background:#0c141e}.mini span{display:block;color:#9eacc0;font-size:9px}.mini b{display:block;margin-top:3px;color:#edf2f8;font-size:11px}.identity{display:grid;gap:9px;margin-top:9px}.identity>div{display:grid;gap:3px}.identity span,.data-token-main span,.muted-small{color:var(--muted);font-size:10px}.identity b{font-size:11px}.identity code,.address-block div{display:block;word-break:break-all;color:#d2deed;font-size:10px;line-height:1.45}
.validation-top{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:9px}.validation-card{padding:13px;border:1px solid #2a394d;border-radius:15px;background:#111925}.validation-card span{color:#a0adbf;font-size:10px}.validation-card b{display:block;margin-top:5px;color:#f1f5fb;font-size:20px}.bucket{padding:12px 0;border-top:1px solid #2a394d}.bucket>summary{cursor:pointer;list-style:none}.bucket>summary::-webkit-details-marker{display:none}.bucket>summary:after{content:"+";float:right;color:var(--muted);font-size:16px}.bucket[open]>summary:after{content:"−"}.bucket-head{display:flex;justify-content:space-between;color:#e5ebf3;font-size:11px;font-weight:900}.bucket-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:7px;margin-top:9px}.data-token-list{display:grid;gap:7px;margin-top:9px}.data-token{padding:10px;border:1px solid #2a394d;border-radius:12px;background:#0c141e}.data-token-main{display:flex;justify-content:space-between;align-items:center;gap:8px}.data-token-main b{font-size:12px}.data-token-metrics{display:grid;grid-template-columns:repeat(3,1fr);gap:6px;margin-top:8px}.data-token-metrics span{color:var(--muted);font-size:9px}.data-token-metrics b{display:block;margin-top:2px;color:#e7edf6;font-size:10px}.address-block{margin-top:8px}.muted-small{margin-top:5px}
.analytics-summary{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:9px}.validation-top{grid-template-columns:repeat(4,minmax(0,1fr))}.validation-card{padding:13px 14px}.validation-card small{display:block;margin-top:6px;color:#8797ac;font-size:9px;line-height:1.4}.analytics-section{margin-top:13px;padding:17px;border:1px solid #29394e;border-radius:17px;background:linear-gradient(150deg,#141e2b,#101722)}.analytics-section-head{display:flex;justify-content:space-between;align-items:flex-end;gap:12px;margin-bottom:13px}.analytics-section h3{margin:0;color:#edf2f8;font-size:15px}.analytics-section-head p{margin:5px 0 0;color:var(--muted);font-size:11px;line-height:1.45}.bucket-grid-new{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px}.bucket-card{min-width:0;padding:14px;border:1px solid #2a394d;border-radius:14px;background:#0c141e}.bucket-card-top{display:flex;justify-content:space-between;align-items:center;gap:8px}.bucket-name{color:#f1f5fb;font-size:13px;font-weight:900}.bucket-count{padding:5px 8px;border:1px solid #304158;border-radius:999px;color:#b8c6d8;font-size:10px;font-weight:800}.bucket-results{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:7px;margin-top:12px}.bucket-result{min-width:0;padding:9px;border:1px solid #202d3e;border-radius:10px;background:#111b28}.bucket-result span{display:block;color:#9eacc0;font-size:9px}.bucket-result b{display:block;margin-top:4px;color:#edf2f8;font-size:12px}.bucket-result i{display:block;height:4px;margin-top:7px;border-radius:9px;background:#273449;overflow:hidden}.bucket-result i:after{content:"";display:block;width:var(--rate);height:100%;border-radius:9px;background:var(--bar,#79dfa0)}.bucket-result.loss i:after{background:#ff8791}.bucket-extra{margin-top:10px}.bucket-extra summary{cursor:pointer;color:#b9c8da;font-size:10px;font-weight:800}.data-token-list{grid-template-columns:repeat(2,minmax(0,1fr))}.data-token-main{justify-content:flex-start}.data-token-main>div{min-width:0}.data-token-main b{display:block}.data-token-name{overflow:hidden;text-overflow:ellipsis;white-space:nowrap;color:var(--muted);font-size:9px}.data-token-metrics{grid-template-columns:repeat(3,minmax(0,1fr))}.data-token-outcome{margin-top:7px;color:#aebdd0;font-size:9px}.analytics-explainer{margin-top:11px;padding:10px 12px;border-radius:10px;background:#0b131d;color:#9eacc0;font-size:10px;line-height:1.5}.token-info-note{margin:9px 0 0;color:#8f9eb2;font-size:9px;line-height:1.5}
.warning{margin-bottom:12px;padding:12px 14px;border:1px solid #66512b;border-radius:13px;background:#302713;color:#ffd178;font-size:12px;font-weight:750}.error{margin:10px 0;padding:11px 12px;border:1px solid #69313b;border-radius:12px;background:#321920;color:#ff9ca5;font-size:12px}.empty{padding:30px 20px;border:1px dashed #304158;border-radius:17px;background:#0d141e;color:#a0adbf;text-align:center;font-size:13px;line-height:1.6}
dialog.risk-dialog{width:min(460px,calc(100% - 28px));padding:0;border:1px solid #35455b;border-radius:18px;background:#111925;color:#edf2f8;box-shadow:0 24px 80px #0009}dialog.risk-dialog::backdrop{background:#000b;backdrop-filter:blur(4px)}.risk-dialog-inner{padding:22px}.risk-dialog h2{margin:0 0 7px;color:#ffd178;font-size:20px}.risk-dialog p{margin:8px 0;color:#b7c3d2;font-size:13px;line-height:1.55}.risk-list{margin:13px 0;padding-left:20px;color:#ffc0a3;font-size:13px;line-height:1.55}.risk-actions{display:flex;justify-content:flex-end;gap:8px;flex-wrap:wrap;margin-top:18px}.risk-actions button{padding:10px 13px;border-radius:10px;font-size:12px;font-weight:800}.risk-cancel{background:#222d3c;color:#e1e8f1}.risk-continue{background:#865323;color:#fff}
 .nav{position:fixed;z-index:100;left:0;top:0;bottom:0;width:226px;padding:24px 13px;background:#0c121b;border-right:1px solid #243247}.nav:before{content:"MEME AI";display:block;margin:2px 10px 27px;color:#9cf0b8;font-size:13px;font-weight:950;letter-spacing:.13em}.nav-inner{display:grid;gap:7px}.nav-btn{display:flex;align-items:center;gap:12px;width:100%;padding:12px 13px;border-radius:12px;background:transparent;color:#9baabd;text-align:left;font-size:12px;font-weight:800}.nav-btn:hover{background:#131e2c;color:#e7edf6}.nav-btn.active{background:#172b22;color:#9af0b8;box-shadow:inset 3px 0 #79dfa0}.nav-icon{width:21px;flex:none;text-align:center;font-size:17px;line-height:19px}
@media(min-width:901px){.app{width:calc(100% - 270px);max-width:1220px;margin:0 20px 0 250px}}
@media(max-width:900px){.app{max-width:1220px;margin:0 auto;padding:18px 14px calc(100px + env(safe-area-inset-bottom))}.nav{top:auto;right:0;bottom:0;width:auto;height:auto;padding:8px 10px calc(8px + env(safe-area-inset-bottom));background:#0b111bf2;border-top:1px solid #28364a;border-right:0;backdrop-filter:blur(18px)}.nav:before{display:none}.nav-inner{max-width:600px;margin:auto;grid-template-columns:repeat(4,1fr);gap:5px}.nav-btn{display:flex;flex-direction:column;justify-content:center;gap:3px;padding:7px 5px;border-radius:11px;text-align:center;font-size:10px}.nav-btn.active{box-shadow:inset 0 2px #79dfa0}.nav-icon{font-size:16px}}
@media(max-width:680px){.header{margin-bottom:16px}.hero{padding:18px;border-radius:19px}.hero h2{font-size:25px}.hero-stats{grid-template-columns:repeat(2,minmax(0,1fr));gap:8px}.hero-stat{padding:11px}.hero-stat b{font-size:20px}.section-head{margin-top:22px}.list{grid-template-columns:1fr;gap:10px}.token{padding:14px}.validation-top{grid-template-columns:repeat(2,minmax(0,1fr))}.history-grid{grid-template-columns:repeat(3,minmax(0,1fr))}.bucket-grid{grid-template-columns:repeat(2,minmax(0,1fr))}}
@media(max-width:430px){.app{padding:13px 11px calc(92px + env(safe-area-inset-bottom))}.brand h1{font-size:21px}.brand p{font-size:11px}.logo{width:40px;height:40px}.scan-btn{min-width:88px;height:42px;padding:0 12px}.hero-top{align-items:center}.hero h2{font-size:22px}.hero-copy{font-size:12px}.hero-stat span{font-size:10px}.section-head h2{font-size:18px}.section-head p{font-size:11px}.filters-row select{flex:1;min-width:135px}.keygrid{grid-template-columns:repeat(2,minmax(0,1fr))}.forecast-cell{padding:9px 7px}.forecast-cell span{font-size:8px}.forecast-cell b{font-size:11px}.factor-grid{grid-template-columns:repeat(2,minmax(0,1fr))}.history-grid{grid-template-columns:repeat(2,minmax(0,1fr))}.nav-btn{font-size:9px}}
@media(max-width:680px){.bucket-grid-new{grid-template-columns:1fr}.data-token-list{grid-template-columns:1fr}.analytics-section{padding:13px}.analytics-section-head{align-items:flex-start}}@media(max-width:430px){.bucket-results{gap:5px}.bucket-result{padding:7px 6px}.bucket-result span{font-size:8px}.bucket-result b{font-size:11px}.bucket-name{font-size:12px}}
</style>
</head>
<body>
<div class="app">
<header class="header">
  <div class="brand">
    <div class="logo">MA</div>
    <div><h1>Meme AI</h1><p><span class="status-dot"></span>Aprendizagem ativa · Solana · V2.7</p></div>
  </div>
  <button class="scan-btn" id="scanButton" onclick="runScan()">SCAN</button>
</header>

<section class="hero">
  <div class="hero-top">
    <div>
      <div class="kicker">Mercado agora</div>
      <h2 id="heroTitle">A procurar oportunidades</h2>
      <p class="hero-copy" id="status">A carregar dados do scanner...</p>
      <div class="last-scan" id="lastScan">Último scan: —</div>
    </div>
    <div class="count-pill" id="modePill">LIVE</div>
  </div>
  <div class="hero-stats">
    <div class="hero-stat"><span>Tokens</span><b id="count">—</b></div>
    <div class="hero-stat"><span>Sinais IA</span><b id="alerts">—</b></div>
    <div class="hero-stat"><span>Acompanhados</span><b id="historyCount">0</b></div>
    <div class="hero-stat"><span>+25%</span><b id="wins">0</b></div>
  </div>
</section>

<section id="scanSection" class="section active">
  <div class="section-head"><div><h2>Scanner</h2><p>Previsões por prazo e sinais validados com resultados recentes.</p></div><span class="count-pill" id="scanCountPill">0 tokens</span></div>
  <div class="filters-row">
    <select id="filter" onchange="render()"><option value="all">Todos os tokens</option><option value="ai">Sinais IA validados</option><option value="top">Top oportunidades</option><option value="alerts">Alertas do score</option><option value="lowrisk">Risco ≤35</option><option value="young">Até 30 min</option></select>
    <select id="sort" onchange="render()"><option value="adjusted">Melhor score ajustado</option><option value="opp">Maior oportunidade</option><option value="risk">Menor risco</option><option value="age">Mais recentes</option><option value="volume">Maior volume 1h</option></select>
  </div>
  <div id="scanError"></div>
  <div id="list" class="list"></div>
</section>

<section id="topSection" class="section">
  <div class="section-head"><div><h2>🔥 Top oportunidades</h2><p>Lista curta para leitura rápida.</p></div><span class="count-pill" id="topCount">0</span></div>
  <div class="info-card"><h3>Como entra no Top</h3><p>Score ajustado ≥ <b>55</b> · Risco ≤ <b>55</b> · Liquidez ≥ <b>$10K</b>.</p><p>O scanner encontra tokens por perfis, promoções e atividade da comunidade. Uma promoção paga ajuda a encontrar o token, mas não indica que seja bom.</p><p>Score ajustado = Oportunidade − (Risco × 0,45). É uma métrica experimental, não uma previsão de retorno.</p></div>
  <div id="topList" class="list" style="margin-top:10px"></div>
</section>

<section id="historySection" class="section">
  <div class="section-head"><div><h2>Histórico</h2><p>Alertas guardados na D1 e acompanhados ao longo do tempo.</p></div><span class="count-pill" id="historyPill">0</span></div>
  <div class="info-card"><h3>O que estás a ver</h3><p>Um token entra aqui quando a Oportunidade é ≥ <b>72</b> e o Risco é ≤ <b>55</b>. O histórico guarda o preço inicial, a subida máxima, a queda desde o pico e os marcos de +10%, +25% e -20%.</p></div>
  <div id="history" class="history-list" style="margin-top:10px"></div>
</section>

<section id="dataSection" class="section">
  <div class="section-head"><div><h2>Aprendizagem</h2><p>Modelos supervisionados com resultados observados em 1h, 24h e 7d.</p></div><button class="count-pill" onclick="loadAnalytics()">Atualizar</button></div>
  <div id="analytics"></div>
  <div class="info-card"><h3>Como interpretar</h3><p>As estimativas só aparecem após 100 exemplos completos por prazo. São probabilidades aprendidas de movimentos históricos, não garantias nem instruções automáticas para investir.</p></div>
</section>
</div>

<dialog id="riskDialog" class="risk-dialog" aria-labelledby="riskDialogTitle" aria-describedby="riskDialogMessage">
  <div class="risk-dialog-inner">
    <h2 id="riskDialogTitle">Riscos detetados</h2>
    <p id="riskDialogMessage">Este token apresenta sinais de risco:</p>
    <ul id="riskDialogList" class="risk-list"></ul>
    <p>A app não compra tokens. Continuar apenas abre o gráfico do par no DEX Screener.</p>
    <div class="risk-actions"><button type="button" class="risk-cancel" onclick="closeRiskDialog()">Voltar</button><button type="button" class="risk-continue" onclick="confirmOpenToken()">Abrir gráfico mesmo assim</button></div>
  </div>
</dialog>

<nav class="nav" aria-label="Navegação principal"><div class="nav-inner">
<button class="nav-btn active" data-target="scanSection" onclick="showSection('scanSection',this)"><span class="nav-icon">⌁</span>Scan</button>
<button class="nav-btn" data-target="topSection" onclick="showSection('topSection',this)"><span class="nav-icon">★</span>Top</button>
<button class="nav-btn" data-target="historySection" onclick="showSection('historySection',this)"><span class="nav-icon">◷</span>Histórico</button>
<button class="nav-btn" data-target="dataSection" onclick="showSection('dataSection',this)"><span class="nav-icon">▦</span>Dados</button>
</div></nav>

<script>
let tokens=[];let historyData=[];let analyticsData=null;let activeSection='scanSection';
function num(v,fallback=0){const n=Number(v);return Number.isFinite(n)?n:fallback}
function money(v){const n=Number(v);if(!Number.isFinite(n))return '—';if(n>=1e9)return '$'+(n/1e9).toFixed(2)+'B';if(n>=1e6)return '$'+(n/1e6).toFixed(2)+'M';if(n>=1e3)return '$'+(n/1e3).toFixed(1)+'K';return '$'+n.toFixed(n<1?6:0)}
function age(v){const n=Number(v);if(!Number.isFinite(n))return '—';if(n<60)return Math.max(1,Math.round(n))+'m';if(n<1440)return Math.round(n/60)+'h';return Math.round(n/1440)+'d'}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function signedPct(v){const n=num(v);return (n>0?'+':'')+n.toFixed(1)+'%'}
function pctClass(v){const n=num(v);return n>0?'positive':n<0?'negative':'neutral'}
function updateStats(){document.getElementById('historyCount').textContent=historyData.length;document.getElementById('wins').textContent=historyData.filter(x=>x.hit25_at||x.result==='hit25').length;document.getElementById('historyPill').textContent=historyData.length}
function hasAiSignal(x){return Object.values(x?.forecasts||{}).some(f=>f?.ready&&f.validated&&num(f.probabilityUp)>=65&&num(f.expectedReturnPct)>0&&num(x?.risk)<=55&&num(x?.liquidity)>=10000&&num(x?.adjustedScore)>=55)}
function tokenQuality(x){if(hasAiSignal(x))return {label:'Sinal favorável',className:'quality-favorable'};if(num(x?.risk)>55||num(x?.liquidity)<10000||num(x?.adjustedScore)<45)return {label:'Risco elevado',className:'quality-high-risk'};if(!Object.values(x?.forecasts||{}).some(f=>f?.ready&&f.validated))return {label:'A aprender',className:'quality-learning'};return {label:'Atenção',className:'quality-caution'}}
function forecastHtml(x){const fs=x?.forecasts||{},items=[['short','Curto · 1h'],['medium','Médio · 24h'],['long','Longo · 7d']];const cells=items.map(([k,label])=>{const f=fs[k];return '<div class="forecast-cell"><span>'+label+'</span>'+(f?.ready?'<b>Prob. de subida '+num(f.probabilityUp)+'%</b><span>Retorno estimado '+signedPct(f.expectedReturnPct)+'</span><span>'+num(f.samples)+' amostras</span><span>Validação '+num(f.validationBalancedAccuracy)+'% ('+num(f.validationSamples)+')</span>':'<b>A aprender</b><span>'+num(f?.samples)+' / 100 amostras</span>')+'</div>'}).join('');return '<div class="forecast-grid">'+cells+'</div>'+(hasAiSignal(x)?'<span class="model-signal">SINAL IA · valida também o risco</span>':'')+'<div class="forecast-note">Estimativas supervisionadas: treino nos exemplos mais antigos e validação nos mais recentes. A probabilidade ainda não está calibrada e não garante retorno.</div>'}
function socialLinksHtml(x){const links=Array.isArray(x?.socialLinks)?x.socialLinks:[];const buttons=links.map(s=>{try{const u=new URL(s.url);if(u.protocol!=='https:')return '';const label=String(s.label||'Social').slice(0,24),icon=label==='Website'?'↗':label==='Telegram'?'➤':label==='X'?'𝕏':label.slice(0,1);return '<a class="social-link" href="'+esc(u.href)+'" target="_blank" rel="noopener noreferrer"><span class="social-link-icon">'+esc(icon)+'</span>'+esc(label)+'<span aria-hidden="true">↗</span></a>'}catch{return ''}}).join('');return buttons?'<div class="social-block"><div class="social-title">Perfis e site</div><div class="social-links">'+buttons+'</div><div class="social-note">Links listados pelo DEX Screener; isto não é análise do que a comunidade diz.</div></div>':''}
let pendingPairUrl='';
function requestOpenToken(address){const x=tokens.find(t=>t?.address===address);if(!x?.url)return;let parsed;try{parsed=new URL(x.url)}catch{return}if(parsed.protocol!=='https:'||!(parsed.hostname==='dexscreener.com'||parsed.hostname.endsWith('.dexscreener.com')))return;const state=tokenQuality(x);if(state.className==='quality-favorable'){window.open(parsed.href,'_blank','noopener,noreferrer');return}const warnings=Array.isArray(x.riskFlags)?[...x.riskFlags]:[];if(num(x.risk)>55)warnings.push('Índice de risco elevado: '+num(x.risk)+'/100.');if(num(x.liquidity)<10000)warnings.push('Liquidez muito baixa: '+money(x.liquidity)+'.');if(num(x.adjustedScore)<45)warnings.push('Score ajustado baixo: '+num(x.adjustedScore)+'/100.');if(!Object.values(x.forecasts||{}).some(f=>f?.ready&&f.validated))warnings.push('Ainda não existe previsão IA validada para este prazo.');else if(!hasAiSignal(x))warnings.push('O modelo não gerou um sinal favorável para este token.');pendingPairUrl=parsed.href;document.getElementById('riskDialogTitle').textContent=state.label+': $'+(x.symbol||'TOKEN');document.getElementById('riskDialogList').innerHTML=[...new Set(warnings)].map(w=>'<li>'+esc(w)+'</li>').join('')||'<li>Os critérios de qualidade do scanner não foram cumpridos.</li>';const dialog=document.getElementById('riskDialog');if(dialog.showModal)dialog.showModal();else if(window.confirm('Sinais de risco: '+warnings.join(' · ')+'\\n\\nAbrir o gráfico?'))confirmOpenToken()}
function closeRiskDialog(){document.getElementById('riskDialog').close();pendingPairUrl=''}
function confirmOpenToken(){const url=pendingPairUrl;document.getElementById('riskDialog').close();pendingPairUrl='';if(url)window.open(url,'_blank','noopener,noreferrer')}
function tokenCard(x,i){
 const adjusted=num(x?.adjustedScore),opp=num(x?.opportunity),risk=num(x?.risk),f=x?.factors||{},flags=Array.isArray(x?.riskFlags)?x.riskFlags:[],quality=tokenQuality(x);
 return '<article class="token '+(x?.alert?'alert':'')+'">'+
  '<div class="token-head"><div class="token-main"><div class="rank">#'+(i+1)+'</div><div><div class="symbol">$'+esc(x?.symbol||'TOKEN')+'</div><div class="name">'+esc(x?.name||'Unknown')+'</div><div class="badges"><span class="badge">'+age(x?.ageMin)+'</span><span class="badge">'+esc(x?.dex||'—')+'</span>'+(x?.discoverySources?.includes('boost')?'<span class="badge">PROMOVIDO</span>':'')+(x?.discoverySources?.includes('tracked')?'<span class="badge">ACOMPANHADO</span>':'')+(x?.alert?'<span class="badge alert">ALERTA SCORE</span>':'')+(hasAiSignal(x)?'<span class="badge alert">SINAL IA</span>':'')+'</div></div></div><div class="scorebox"><div class="score">'+adjusted+'</div><div class="scorelabel">SCORE AJUSTADO</div></div></div>'+
  '<div class="quality-pill '+quality.className+'">'+quality.label+'</div>'+socialLinksHtml(x)+'<div class="scorebar"><i style="width:'+Math.max(0,Math.min(100,adjusted))+'%"></i></div>'+forecastHtml(x)+
  '<div class="keygrid">'+
   '<div class="metric"><span>Liquidez</span><b>'+money(x?.liquidity)+'</b></div>'+
   '<div class="metric"><span>Preço · 5 min</span><b class="'+pctClass(x?.change5m)+'">'+signedPct(x?.change5m)+'</b></div>'+
   '<div class="metric"><span>Rácio compras/vendas</span><b>'+num(x?.buySell).toFixed(2)+'x</b></div>'+
   '<div class="metric"><span>Risco · 0–100</span><b class="'+(risk<=35?'positive':risk>55?'negative':'neutral')+'">'+risk+'/100</b></div>'+
  '</div>'+
  '<details class="details"><summary>Ver análise completa</summary><div class="factor-grid">'+
   '<div class="factor"><span>Impulso</span><b>'+num(f.momentum)+'/25</b></div><div class="factor"><span>Liquidez</span><b>'+num(f.liquidity)+'/20</b></div><div class="factor"><span>Atividade</span><b>'+num(f.activity)+'/20</b></div><div class="factor"><span>Fluxo</span><b>'+num(f.flow)+'/20</b></div><div class="factor"><span>Recência</span><b>'+num(f.freshness)+'/15</b></div><div class="factor"><span>Oportunidade</span><b>'+opp+'/100</b></div>'+
  '</div><div class="keygrid" style="margin-top:6px"><div class="metric"><span>Capitalização</span><b>'+money(x?.marketCap)+'</b></div><div class="metric"><span>Volume 5m</span><b>'+money(x?.volume5m)+'</b></div><div class="metric"><span>Volume 1h</span><b>'+money(x?.volume1h)+'</b></div><div class="metric"><span>Transações 5m</span><b>'+num(x?.tx5m)+'</b></div><div class="metric"><span>Rácio compras/vendas</span><b>'+num(x?.buys)+' / '+num(x?.sells)+'</b></div></div>'+
  '<div class="flags">'+(flags.length?'⚠ '+esc(flags.join(' · ')):'✓ Sem flags fortes de risco')+'</div><div class="token-info-note">O score resume sinais do scanner; risco e liquidez devem ser lidos em conjunto. Estimativas não são garantias.</div><div class="address">'+esc(x?.address||'')+'</div><div style="margin-top:7px"><button type="button" class="open-token-btn" data-token-address="'+esc(x?.address||'')+'">Abrir par no DEX Screener ↗</button></div></details></article>'
}
function filtered(list){let a=[...list],f=document.getElementById('filter')?.value||'all';if(f==='ai')a=a.filter(hasAiSignal);if(f==='top')a=a.filter(x=>num(x?.adjustedScore)>=55&&num(x?.risk)<=55&&num(x?.liquidity)>=10000);if(f==='alerts')a=a.filter(x=>x?.alert);if(f==='lowrisk')a=a.filter(x=>num(x?.risk)<=35);if(f==='young')a=a.filter(x=>num(x?.ageMin,999999)<=30);let s=document.getElementById('sort')?.value||'adjusted';if(s==='adjusted')a.sort((x,y)=>num(y?.adjustedScore)-num(x?.adjustedScore));if(s==='opp')a.sort((x,y)=>num(y?.opportunity)-num(x?.opportunity));if(s==='risk')a.sort((x,y)=>num(x?.risk)-num(y?.risk));if(s==='age')a.sort((x,y)=>num(x?.ageMin,999999)-num(y?.ageMin,999999));if(s==='volume')a.sort((x,y)=>num(y?.volume1h)-num(x?.volume1h));return a}
function wireTokenButtons(root){root.querySelectorAll('[data-token-address]').forEach(b=>b.addEventListener('click',()=>requestOpenToken(b.dataset.tokenAddress)))}
function render(){const a=filtered(tokens),list=document.getElementById('list');document.getElementById('scanCountPill').textContent=a.length+' tokens';list.innerHTML=a.length?a.map(tokenCard).join(''):'<div class="empty">Sem resultados para este filtro.<br><br>Tenta outro filtro ou faz um novo scan.</div>';wireTokenButtons(list);renderTop()}
function renderTop(){const a=[...tokens].filter(x=>num(x?.adjustedScore)>=55&&num(x?.risk)<=55&&num(x?.liquidity)>=10000).sort((x,y)=>num(y?.adjustedScore)-num(x?.adjustedScore)),list=document.getElementById('topList');document.getElementById('topCount').textContent=a.length+' tokens';list.innerHTML=a.length?a.slice(0,20).map(tokenCard).join(''):'<div class="empty">Ainda não existem tokens que cumpram os critérios do Top.</div>';wireTokenButtons(list)}
function resultLabel(x){if(x?.hit25_at||x?.result==='hit25')return ['🎯 +25%','positive'];if(x?.hit10_at||x?.result==='hit10')return ['🟢 +10%','positive'];if(x?.stop20_at||x?.result==='stop20')return ['🔴 -20%','negative'];return ['🟡 A acompanhar','neutral']}
function minsLabel(first,at){if(!first||!at)return '—';const m=Math.max(0,(num(at)-num(first))/60000);if(m<60)return Math.round(m)+' min';if(m<1440)return (m/60).toFixed(1)+' h';return (m/1440).toFixed(1)+' d'}
function historyCard(x){const initial=num(x?.initial_price),current=num(x?.current_price),initialMcap=num(x?.initial_mcap),currentMcap=num(x?.current_mcap),priceChange=initial>0?((current-initial)/initial)*100:0,mcapChange=initialMcap>0?((currentMcap-initialMcap)/initialMcap)*100:0;const r=resultLabel(x);return '<article class="history-card"><div class="history-head"><div><div class="history-symbol">$'+esc(x?.symbol||'TOKEN')+'</div><div class="name">'+esc(x?.name||'')+' · '+(x?.first_seen?new Date(num(x.first_seen)).toLocaleString('pt-PT'):'—')+'</div></div><div class="history-status '+r[1]+'">'+r[0]+'</div></div><div class="history-grid"><div class="mini"><span>Cap. inicial</span><b>'+money(initialMcap)+'</b></div><div class="mini"><span>Cap. atual</span><b>'+money(currentMcap)+'</b></div><div class="mini"><span>Variação cap.</span><b class="'+pctClass(mcapChange)+'">'+signedPct(mcapChange)+'</b></div><div class="mini"><span>Preço atual</span><b>'+money(current)+'</b></div><div class="mini"><span>Variação preço</span><b class="'+pctClass(priceChange)+'">'+signedPct(priceChange)+'</b></div><div class="mini"><span>Score inicial</span><b>'+num(x?.initial_adjusted_score)+'</b></div><div class="mini"><span>Risco inicial</span><b>'+num(x?.initial_risk)+'</b></div><div class="mini"><span>Máximo</span><b class="positive">'+signedPct(x?.peak_pct)+'</b></div><div class="mini"><span>Queda desde pico</span><b class="negative">'+signedPct(x?.max_drawdown_pct)+'</b></div><div class="mini"><span>Até +10%</span><b>'+minsLabel(x?.first_seen,x?.hit10_at)+'</b></div><div class="mini"><span>Até +25%</span><b>'+minsLabel(x?.first_seen,x?.hit25_at)+'</b></div><div class="mini"><span>Até -20%</span><b>'+minsLabel(x?.first_seen,x?.stop20_at)+'</b></div></div><details class="details"><summary>Ver identidade e endereço</summary><div class="identity"><div><span>Nome</span><b>'+esc(x?.name||'—')+'</b></div><div><span>Endereço</span><code>'+esc(x?.address||'—')+'</code></div><div><span>Última atualização</span><b>'+(x?.last_seen?new Date(num(x.last_seen)).toLocaleString('pt-PT'):'—')+'</b></div></div></details></article>'}
function renderHistory(){document.getElementById('history').innerHTML=historyData.length?historyData.slice(0,60).map(historyCard).join(''):'<div class="empty">Ainda não há alertas guardados.</div>'}
function time(v){if(v===null||v===undefined)return '—';const n=num(v);if(n<60)return Math.round(n)+'m';if(n<1440)return (n/60).toFixed(1)+'h';return (n/1440).toFixed(1)+'d'}
function analyticsBucketHtml(name,b){b=b||{};const total=num(b.total),items=Array.isArray(b.tokens)?b.tokens:[];const pct=(n)=>total?(num(n)/total*100).toFixed(1):'0.0';const results=[['+10%',b.hit10,'#79dfa0',''],['+25%',b.hit25,'#79dfa0',''],['-20%',b.stop20,'#ff8791','loss']].map(([label,value,color,cls])=>'<div class="bucket-result '+cls+'"><span>'+label+' observado</span><b>'+num(value)+' · '+pct(value)+'%</b><i style="--rate:'+pct(value)+'%;--bar:'+color+'"></i></div>').join('');const list=items.map(x=>'<div class="data-token"><div class="data-token-main"><div><b>$'+esc(x.symbol||'TOKEN')+'</b><div class="data-token-name">'+esc(x.name||'')+'</div></div></div><div class="data-token-metrics"><span>Score ajustado<b>'+num(x.score)+'/100</b></span><span>Risco inicial<b>'+num(x.risk)+'/100</b></span><span>Cap. atual<b>'+money(x.currentMcap)+'</b></span></div><div class="data-token-outcome">'+(x.result==='tracking'?'Em acompanhamento':x.result==='hit10'?'Atingiu +10%':x.result==='hit25'?'Atingiu +25%':x.result==='stop20'?'Atingiu -20%':'Estado: '+esc(x.result))+' · Inicial: '+money(x.initialMcap)+'</div><details class="details"><summary>Ver endereço</summary><div class="address-block"><div>'+esc(x.address||'—')+'</div></div></details></div>').join('');return '<article class="bucket-card"><div class="bucket-card-top"><span class="bucket-name">Score '+esc(name)+'</span><span class="bucket-count">'+total+' acompanhados</span></div><div class="bucket-results">'+results+'</div><div class="mini" style="margin-top:8px"><span>Subida média máxima observada</span><b>'+num(b.avgPeak).toFixed(1)+'%</b></div>'+(items.length?'<details class="bucket-extra"><summary>Ver tokens desta faixa ('+items.length+(total>items.length?' de '+total:'')+')</summary><div class="data-token-list">'+list+'</div></details>':'<div class="data-token-outcome">Ainda sem tokens nesta faixa.</div>')+'</article>'}
function renderAnalytics(){const el=document.getElementById('analytics');const a=analyticsData;if(!a){el.innerHTML='<div class="empty">Sem dados de validação.</div>';return}const r=a.rates||{},av=a.averages||{},names=['<45','45-54','55-64','65-74','75-84','85+'];el.innerHTML='<div class="validation-top"><div class="validation-card"><span>Tokens acompanhados</span><b>'+num(a.tracked)+'</b><small>Registos com histórico guardado</small></div><div class="validation-card"><span>Atingiram +10%</span><b>'+num(a.hit10)+' · '+num(r.hit10).toFixed(1)+'%</b><small>Sobre todos os acompanhados</small></div><div class="validation-card"><span>Atingiram +25%</span><b>'+num(a.hit25)+' · '+num(r.hit25).toFixed(1)+'%</b><small>Sobre todos os acompanhados</small></div><div class="validation-card"><span>Caíram -20%</span><b>'+num(a.stop20)+' · '+num(r.stop20).toFixed(1)+'%</b><small>Sobre todos os acompanhados</small></div><div class="validation-card"><span>Em acompanhamento</span><b>'+num(a.tracking)+'</b><small>Sem marco registado até agora</small></div><div class="validation-card"><span>Pico médio observado</span><b>'+num(av.peakPct).toFixed(1)+'%</b><small>Movimento máximo desde a entrada</small></div><div class="validation-card"><span>Observações de mercado</span><b>'+num(a.observations)+'</b><small>Registos usados na aprendizagem</small></div></div><section class="analytics-section"><div class="analytics-section-head"><div><h3>Resultados por score ajustado</h3><p>Compara o que aconteceu depois de cada token entrar no acompanhamento.</p></div></div><div class="bucket-grid-new">'+names.map(n=>analyticsBucketHtml(n,(a.buckets||{})[n])).join('')+'</div><div class="analytics-explainer">As faixas mostram eventos observados por total de tokens acompanhados; um token pode ter atingido +10% e depois +25%, por isso as percentagens não somam 100%. Tokens sem marco continuam em acompanhamento. Histórico passado não garante resultados futuros.</div></section><section class="analytics-section"><div class="analytics-section-head"><div><h3>Tempo médio até aos marcos</h3><p>Calculado apenas nos tokens que atingiram cada nível.</p></div></div><div class="history-grid"><div class="mini"><span>Até +10%</span><b>'+time(av.minutesTo10)+'</b></div><div class="mini"><span>Até +25%</span><b>'+time(av.minutesTo25)+'</b></div><div class="mini"><span>Até -20%</span><b>'+time(av.minutesToStop20)+'</b></div><div class="mini"><span>Queda média desde o pico</span><b>'+num(av.maxDrawdownPct).toFixed(1)+'%</b></div></div></section>'}
function showSection(id,button){activeSection=id;document.querySelectorAll('.section').forEach(s=>s.classList.remove('active'));const el=document.getElementById(id);if(el)el.classList.add('active');document.querySelectorAll('.nav-btn').forEach(b=>b.classList.remove('active'));if(button)button.classList.add('active');window.scrollTo({top:0,behavior:'smooth'});if(id==='topSection')renderTop();if(id==='historySection')renderHistory();if(id==='dataSection'&&!analyticsData)loadAnalytics()}
async function loadScan(){const status=document.getElementById('status'),error=document.getElementById('scanError');status.textContent='A fazer scan...';error.innerHTML='';document.getElementById('heroTitle').textContent='A atualizar mercado';const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),10000);try{const r=await fetch('/api/scan',{cache:'no-store',signal:controller.signal});const data=await r.json().catch(()=>null);if(!r.ok)throw new Error(data?.error||('HTTP '+r.status));tokens=Array.isArray(data?.tokens)?data.tokens:[];document.getElementById('count').textContent=num(data?.count);document.getElementById('alerts').textContent=num(data?.alerts);const stamp=data?.at?new Date(data.at):new Date();document.getElementById('lastScan').textContent='Último scan: '+stamp.toLocaleTimeString('pt-PT');const ss=data?.sourceStatus||{},partial=data?.batchesFailed>0||Object.values(ss).includes('partial');status.textContent=tokens.length?('Scan concluído · '+num(data?.discovered)+' candidatos · '+(partial?'parcial · ':'')+'ordenado por score ajustado'):(Object.values(ss).includes('error')?'Scan parcial · algumas fontes indisponíveis':'Sem tokens encontrados');document.getElementById('heroTitle').textContent=tokens.length?(num(data?.alerts)+' alertas · '+tokens.length+' tokens'):'Nenhuma oportunidade agora';if(partial||Object.values(ss).includes('error')){const details=[];if(ss.profiles==='error')details.push('Profiles indisponível');if(ss.boosts==='error')details.push('Boosts indisponível');if(ss.community==='error')details.push('Community indisponível');if(data?.batchesFailed)details.push(num(data.batchesFailed)+' lote(s) de pares falharam');error.innerHTML='<div class="warning">⚠️ Scan parcial'+(details.length?' · '+esc(details.join(' · ')):'')+'</div>'}render()}catch(err){console.error(err);document.getElementById('heroTitle').textContent='Scan interrompido';status.textContent=err?.name==='AbortError'?'O scan excedeu 10s e foi interrompido.':'O scanner não conseguiu concluir o pedido.';error.innerHTML='<div class="error">Erro no scan: '+esc(err?.message||err)+'</div>'}finally{clearTimeout(timer)}}
async function loadHistory(){try{const r=await fetch('/api/history',{cache:'no-store'});if(!r.ok)throw new Error('HTTP '+r.status);const data=await r.json();historyData=Array.isArray(data)?data:[];updateStats();renderHistory()}catch(err){console.error('history',err)}}
async function loadAnalytics(){const el=document.getElementById('analytics');el.innerHTML='<div class="empty">A calcular validação...</div>';try{const r=await fetch('/api/analytics',{cache:'no-store'});if(!r.ok)throw new Error('HTTP '+r.status);analyticsData=await r.json();renderAnalytics()}catch(err){console.error('analytics',err);el.innerHTML='<div class="error">Erro ao carregar dados: '+esc(err?.message||err)+'</div>'}}
async function runScan(){const button=document.getElementById('scanButton');if(button){button.disabled=true;button.textContent='A SCAN...'}try{await loadScan();await loadHistory();await loadAnalytics()}finally{if(button){button.disabled=false;button.textContent='SCAN'}}}
async function boot(){await Promise.all([loadScan(),loadHistory(),loadAnalytics()])}
setInterval(async()=>{await loadScan();await loadHistory();await loadAnalytics()},300000);boot();
</script>
</body>
</html>`;
}
